plugins:
  - rubocop-minitest

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.3
  Exclude:
    - ".ruby-lsp/**/*"
    - "pkg/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Layout/LineLength:
  Max: 120
  Exclude:
    - "lib/rangu.rb"
    - "test/**/*"

Metrics/BlockLength:
  Exclude:
    - "test/**/*"

Metrics/AbcSize:
  Exclude:
    - "test/**/*"

Metrics/ClassLength:
  Exclude:
    - "test/**/*"

Metrics/MethodLength:
  Exclude:
    - "lib/rangu.rb"

Minitest/MultipleAssertions:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - "test/test_rangu.rb"

Style/RedundantRegexpEscape:
  Exclude:
    - "lib/rangu.rb"

Style/RegexpLiteral:
  Exclude:
    - "lib/rangu.rb"

Style/StringLiterals:
  EnforcedStyle: double_quotes
